# Generated by Django 2.2.1 on 2019-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='item decription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='votes_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
